#!/bin/bash

touch results.txt

echo "getting information ..." 

wget -q -O- https://ssc.ce.sharif.edu/election99/ | grep ورودی  >> results.txt

i=0

while IFS= read -r line
do
	printf "$((i + 1))- "
	if test $i -eq 0; then
		echo $line | cut -d '>' -f 2 | cut -d '<' -f 1
	else
		echo $line | cut -d '<' -f 1
	fi
	let i+=1
done < "results.txt"

rm -f results.txt
